display:
  name: "waveshare_3in52"
  flipped: false

assets:
  - ticker: "^GSPC"
    name: "S&P 500"
  - ticker: "BTC-USD"
    name: "BTC"

candles: true

# Please enter a number in seconds
refresh_delay: 20