display:
  id: "waveshare_3in52"
  flipped: true

assets:
  - ticker: "^GSPC"
    name: "S&P 500"

font: "./Roboto.ttf"
font_variant: "Bold"
font_size: 30

# Please enter a number in seconds
refresh_delay: 20
screen_safe_interval: 86400 # 24 hours
