display:
  id: "waveshare_3in52"
  flipped: false

assets:
  - ticker: "^GSPC"
    name: "S&P 500"
  - ticker: "BTC-USD"
    name: "BTC"
  - ticker: "GOOG"
  - ticker: "MSFT"

chart:
  candles: false
  font: "./Roboto.ttf"
  font_size: 30

# Please enter a number in seconds
refresh_delay: 20
